POST {{host}}/api/create-product
Content-Type: application/json

{
    "nomeProduto": "request nome produto for",
    "precoBase": 10,
    "proRulePriceProduct": {
        "cepInicial": "00000010",
        "cepFinal": "00000019",
        "regiao": "Sao Paulo",
        "cidade": "Sao Paulo",
        "typeEntrega": "PROXIMO_DIA_UTIL"
    }
}