POST {{host}}/api/add-produto
Content-Type: application/json

{
    "productName": "encomenda01",
    "precoBase": 10,
    "quant": 1,
    "productControl": {
        "cepInicial": "00000010",
        "cepFinal": "00000019",
        "regiao": "vila any",
        "cidade": "sao paulo"
    }
}

###
