###

POST {{host}}/api/create-promocao-entrega
Content-Type: application/json

{
    "nomePromocao": "PROXIMO DIA UTIL 2",
    "regiao": "REGIAO 1",
    "descontoPorcentagem": 10
}

###

###

POST {{host}}/api/create-promocao-entrega
Content-Type: application/json

{
    "nomePromocao": "MESMO DIA 2",
    "regiao": "REGIAO 2",
    "descontoPorcentagem": 10
}

###


