POST {{host}}/api/pedidos-add
Content-Type: application/json

{
    "cep": "00000010",
    "logradouro": "rua um",
    "complemento": "complemento um",
    "numero": "1",
    "regiao": "regiao um",
    "cidade": "sao paulo",
    "estado": "sao paulo sp"
}

###

POST {{host}}/api/pedidos-add
Content-Type: application/json

{
    "cep": "00000021",
    "logradouro": "rua um",
    "complemento": "complemento um",
    "numero": "1",
    "regiao": "regiao um",
    "cidade": "sao paulo",
    "estado": "sao paulo sp"
}

###

###

POST {{host}}/api/pedidos-add
Content-Type: application/json

{
    "cep": "00000031",
    "logradouro": "rua um",
    "complemento": "complemento um",
    "numero": "1",
    "regiao": "regiao um",
    "cidade": "sao paulo",
    "estado": "sao paulo sp",
    "dataEntrega": "MESMO_DIA"
}

###
